default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor Production -t lib/main_production.dart --no-tree-shake-icons"
    # gradle(task: "test")
    firebase_app_distribution(
      app: "1:1045357360737:android:c9e545aa279b30afe21c20",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "ahmedhelmy1632000@gmail.com",
      release_notes: "first Fastlane Firebase distribution"
  )
  end
end
